# Generated by Django 3.2 on 2021-04-21 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemoncompetitive', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pokedex',
            new_name='Mon_Names',
        ),
    ]
